spring:
  datasource:
    url: jdbc:postgresql://${RDS_ENDPOINT}:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 20
      minimum-idle: 5
      leak-detection-threshold: 60000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  # Add mail configuration to avoid JavaMailSender issues
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
    default-encoding: UTF-8

server:
  port: 8081
  servlet:
    context-path: /api
  tomcat:
    max-threads: 200
    accept-count: 100

logging:
  level:
    root: WARN
    com.slotizen.venus: INFO
  file:
    name: /opt/slotizen/logs/venus.log
  pattern:
    file: "%d{ISO8601} [%thread] %-5level %logger{36} - %msg%n"

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRATION_MS:3600000}
  refresh-token-expiration-ms: ${JWT_REFRESH_TOKEN_EXPIRATION_MS:604800000}

cors:
  allowed-origins:
    - "https://slotizen.com"
    - "https://www.slotizen.com"
  allowed-methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed-headers:
    - "Authorization"
    - "Content-Type"
    - "Cache-Control"
  allow-credentials: true

app:
  storage:
    provider: local
    local:
      base-dir: /opt/slotizen/uploads
      public-base-url: https://api.slotizen.com/api/static
    max-size-bytes: 5242880
    allowed-content-types:
      - image/png
      - image/jpeg
      - image/jpg
      - image/webp
      - image/gif

# Fix: Disable health group validation and simplify configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      validate-group-membership: false  # Disable validation
  health:
    db:
      enabled: true
    mail:
      enabled: false  # Disable mail health check