spring:
  datasource:
    url: jdbc:postgresql://${RDS_ENDPOINT}:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

server:
  port: 8081
  servlet:
    context-path: /api

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,configprops,mappings
      base-path: /actuator
      cors:
        allowed-origins: "https://slotizen.com,https://www.slotizen.com,http://localhost:8080"
        allowed-methods: GET,POST
        allowed-headers: "*"
  
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
      group:
        readiness:
          include: "readinessState,db,diskSpace"
        liveness:
          include: "livenessState,ping"
    
    info:
      enabled: true
    
    metrics:
      enabled: true
    
    prometheus:
      enabled: true

  health:
    circuitbreakers:
      enabled: true
    db:
      enabled: true
    diskspace:
      enabled: true
    mail:
      enabled: true
  
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

# Custom application info
info:
  app:
    name: Venus - Slotizen Backend
    description: Business booking management system

logging:
  level:
    root: INFO
    com.slotizen.venus: DEBUG
  file:
    name: /opt/slotizen/logs/venus.log

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRATION_MS:3600000}
  refresh-token-expiration-ms: ${JWT_REFRESH_TOKEN_EXPIRATION_MS:604800000}

cors:
  allowed-origins:
    - "https://slotizen.com"
    - "https://www.slotizen.com"
    - "http://localhost:8080"  # for development
  allowed-methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
  allowed-headers:
    - "Authorization"
    - "Content-Type"
    - "Cache-Control"
  allow-credentials: true

app:
  storage:
    provider: local
    local:
      base-dir: /opt/slotizen/uploads
      public-base-url: https://api.slotizen.com/api/static